# Generated by Django 6.0.4 on 2026-07-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='prescription',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions'),
        ),
    ]
