# Generated by Django 6.0.4 on 2026-07-17 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_checkout_prescription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(default='', max_length=100)),
                ('address', models.TextField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('phone', models.IntegerField(max_length=50)),
                ('is_ordered', models.BooleanField(default=False)),
                ('delivery_status', models.CharField(default='pending', max_length=100)),
                ('prescription', models.FileField(blank=True, null=True, upload_to='prescriptions')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
