# Generated by Django 6.0.4 on 2026-07-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_completed',
            field=models.BooleanField(default=False),
        ),
    ]
