# Generated by Django 6.0.4 on 2026-07-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_order_billing_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prescription_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
    ]
