# Generated by Django 6.0.4 on 2026-07-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_order_prescription_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='order',
            name='prescription_status',
        ),
    ]
