# Generated by Django 6.0.4 on 2026-07-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_remove_order_prescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
