# Generated by Django 6.0.4 on 2026-07-04 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
